---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-light-stemcell-builder}

inputs:
- name: builder-src
- name: us-light-stemcell

outputs:
- name: light-stemcell

run:
  path: builder-src/ci/tasks/merge-builds
  args:
    - us-light-stemcell
